project:
  type: book
  output-dir: docs

book:
  title: "Health metrics and the spread of infectious diseases"
  subtitle: "with machine learning applications and spatial model analysis"
  author: "Federica Gazzelloni"
  date: "12/16/2022"
  page-navigation: true
  page-footer:
    left: |
      Health metrics and the spread of infectious diseases, with machine learning applications and spatial model analysis was written by <a href="https://federicagazzelloni.netlify.app/">Federica Gazzelloni</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/cover.png
  favicon: images/cover.png
  repo-url: https://github.com/fgazzelloni/infectious/
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: health_metrics.qmd
      chapters:
        - metrics_hm.qmd
        - components_hm.qmd
        - causes_hm.qmd
        
    - part: modeling.qmd
      chapters:
        - techniques_md.qmd
        - packages_md.qmd
        - prediction_md.qmd
        
    - part: data_visualizations.qmd
      chapters:
        - application_dv.qmd
        - spatials_dv.qmd
        - examples_dv.qmd 
        
    - part: case_studies.qmd
      chapters:
        - covid19_cs.qmd
        - health_cs.qmd
        - summary_cs.qmd  
        
    - conclusions.qmd
    - references.qmd   
    
  appendices:
    - appendix_a.qmd
    - appendix_b.qmd  

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true 
  pdf:
    documentclass: scrreprt
    
    author-meta: "Federica Gazzelloni"
    callout-appearance: simple   

editor: visual

