project:
  type: book
  output-dir: docs

book:
  title: "Health metrics and the spread of infectious diseases"
  subtitle: "with machine learning applications and spatial model analysis"
  author: "Federica Gazzelloni"
  date: "12/16/2022"
  page-navigation: true
  page-footer:
    left: |
      Health metrics and the spread of infectious diseases, with machine learning applications and spatial model analysis was written by <a href="https://federicagazzelloni.netlify.app/">Federica Gazzelloni</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/cover.png
  favicon: images/cover.png
  repo-url: https://github.com/fgazzelloni/infectious/
  repo-branch: main
  repo-actions: [edit, issue]
  
   
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: I_HealthMetrics.qmd
      chapters:
        - 01-Metrics.qmd
        - 02-Components.qmd
        - 03-Causes.qmd
        - 04-Metrics2.qmd
        
    - part: II_Modeling.qmd
      chapters:
        - 05-Techniques.qmd
        - 06-Packages.qmd
        - 07-Prediction.qmd
        
    - part: III_DataVisualizations.qmd
      chapters:
        - 08-Application.qmd
        - 09-Spatials.qmd
        - 10-Examples.qmd 
        
    - part: IV_CaseStudies.qmd
      chapters:
        - 11-Covid19.qmd
        - 12-Health.qmd
        - 13-Summary.qmd  
        
    - conclusions.qmd
    - references.qmd   
    
  appendices:
    - appendixA.qmd
    - appendixB.qmd  

bibliography: references.bib

format:
  html:
    theme: cosmo
    #code-link: false
    code-copy: true
    code-fold: show
    code-summary: "Hide code"
    code-block-border-left: "#ff66c4"
    code-overflow: wrap
    code-block-bg: "gray90"
    linkcolor: "#ff66c4"
    smooth-scroll: true
    link-external-newwindow: true
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
    cite-method: biblatex    
    
    author-meta: "Federica Gazzelloni"
    callout-appearance: simple   

editor: visual
editor_options:
  chunk_output_type: inline
execute: 
  echo: true
  message: false
  warning: false

