project:
  type: book
  output-dir: docs

book:
  title: "Health metrics and the spread of infectious diseases"
  subtitle: "with machine learning applications and spatial model analysis"
  author: "Federica Gazzelloni"
  date: "12/16/2022"
  page-navigation: true
  page-footer:
    left: |
      Health metrics and the spread of infectious diseases, with machine learning applications and spatial model analysis was written by <a href="https://federicagazzelloni.netlify.app/">Federica Gazzelloni</a>.
    right: |
      This book was built with <a href="https://quarto.org/">Quarto</a>.
  cover-image: images/cover.png
  favicon: images/cover.png
  repo-url: https://github.com/fgazzelloni/infectious/
  repo-branch: main
  repo-actions: [edit, issue]
  
  chapters:
    - index.qmd
    - intro.qmd
    
    - part: ch10HealthMetrics.qmd
      chapters:
        - ch11Metrics.qmd
        - ch12Components.qmd
        - ch13Causes.qmd
        - ch14Metrics2.qmd
        
    - part: ch20Modeling.qmd
      chapters:
        - ch21Techniques.qmd
        - ch22Packages.qmd
        - ch23Prediction.qmd
        
    - part: ch30DataVisualizations.qmd
      chapters:
        - ch31Application.qmd
        - ch32Spatials.qmd
        - ch33Examples.qmd 
        
    - part: ch40CaseStudies.qmd
      chapters:
        - ch41Covid19.qmd
        - ch42Health.qmd
        - ch43Summary.qmd  
        
    - conclusions.qmd
    - references.qmd   
    
  appendices:
    - appendixA.qmd
    - appendixB.qmd  

bibliography: references.bib

format:
  html:
    theme: cosmo
    code-link: true
    code-copy: true
    code-fold: true
    linkcolor: "pink"
    # backgroundcolor: "white"
  pdf:
    documentclass: scrreprt
    include-in-header: 
      text: |
        \usepackage{makeidx}
        \makeindex
    include-after-body: 
      text: |
        \printindex
    cite-method: biblatex    
    
    author-meta: "Federica Gazzelloni"
    callout-appearance: simple   

editor: visual
execute: 
  echo: true

