# Health metrics {#sec-health_metrics}

Health metrics are key variables to understand more about the state of health of a population. In this book we'll talk about **numbers of years of life lost (YLLs)** and the **numbers of years lived with disabilities (YLDs)**, to finally identify the key metric of the **DALYs** which means **disability adjusted life years**.\
The numbers of years of life lost by a population in comparison to other population in a different country or to the Global mean trend is what is expected it should be based on the latest study results relative to the well being of a country in terms of the definition of a healthy life. To give an example, let's think about a population whose individuals are living a good life, so defined *healthy life* measured on **life expectancy** established to be 80 years on average, as most of the World population meets this as a deadline.

The part of the population who do not meet this age, but dies earlier, contributes to building blocks of the numbers of years of life lost (YLLs), as well as for all that is related with a healthy living, the numbers of years spent dealing with a disability of different kind contribute to increasing the numbers of years lived with disabilities for a country's population.

To establish the well being, meant as the healthy life defying the state of health of a population, based on the latest findings of the most updated studies, the sum of these two values YLLs and YLDs releases the key metric of DALYs. This metric value is used to quickly identify the level of health of a population compared to a Global review.

In addition, this level is used to improve the proportion of countries who are in need of a better health status recognition. To be more specific, the focus on the numbers of years can help identify the areas where most of the years are lost and need for improvement, whether in facilities, research or investments.

An improvement of health at a Global level is reached when the definition of a **healthy file** is met in most of the countries where it wasn't before.

Furthermore, what we want to analyze are a series of data that are produced taking into account the tables of mortality and future life expectancy these are defined as means that these metrics have been considered important for assessing the state of health of one point population

What we refer to are the health metrics and which refer to the number of years lost due to an increase in mortality or in any case to a mortality trend that is above a certain general level which we can consider as the level optimal health globally.
